name: Check Tokenlist

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-tokenlist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true

      - name: Cache Poetry virtualenv
        uses: actions/cache@v2
        id: cache
        with:
          path: ./.venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: poetry install

      - name: Run tokenlist check and schema validation
        run: |
          poetry run python check_tokenlist.py
          if [ $? -eq 0 ]; then
            echo "No missing tokens. Validating JSON schema..."
            poetry run python validate_schema.py
          else
            echo "Missing tokens found. Skipping JSON schema validation."
            exit 1
          fi

      - name: Upload tokenlist check results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: tokenlist-check-results
          path: tokenlist_check_results.txt
