name: Upload Tokenlist

on:
  workflow_dispatch:

jobs:
  upload-tokenlist:
    runs-on: ubuntu-latest
    environment: tokenlist-check
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: "Setup Python, Poetry and Dependencies"
        uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: 3.11
          poetry-version: 1.8.3
      - name: Upload tokenlist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRPC_KEY: ${{ secrets.DRPC_KEY }}
        run: poetry run python upkeep.py all_networks
